import {
  boolean,
  char,
  date,
  integer,
  pgTable,
  smallint,
  varchar,
  decimal,
} from 'drizzle-orm/pg-core';

export const shotsTable = pgTable('shots', {
  season: smallint('season'),
  teamId: integer('team_id'),
  teamName: varchar('team_name'),
  playerId: integer('player_id'),
  playerName: varchar('player_name'),
  positionGroup: char('position_group', { length: 1 }),
  position: varchar('position', { length: 5 }),
  gameDate: date('game_date'),
  gameId: integer('game_id'),
  homeTeam: char('home_team', { length: 3 }),
  awayTeam: char('away_team', { length: 3 }),
  eventType: varchar('event_type', { length: 20 }),
  shotMade: boolean('shot_made'),
  actionType: varchar('action_type', { length: 50 }),
  shotType: varchar('shot_type', { length: 30 }),
  basicZone: varchar('basic_zone', { length: 40 }),
  zoneName: varchar('zone_name', { length: 20 }),
  zoneAbb: varchar('zone_abb', { length: 2 }),
  zoneRange: varchar('zone_range', { length: 20 }),
  locX: decimal('loc_x', { precision: 2 }),
  locY: decimal('loc_y', { precision: 2 }),
  shotDistance: decimal('shot_distance', { precision: 2 }),
  quarter: smallint('quarter'),
  minsLeft: smallint('mins_left'),
  secsLeft: smallint('secs_left'),
  defRtg: decimal('def_rtg', { precision: 2 }),
  defRtgRank: smallint('def_rtg_rank'),
  offRtg: decimal('off_rtg', { precision: 2 }),
  offRtgRank: smallint('off_rtg_rank'),
  playerHeight: decimal('player_height', { precision: 2 }),
  playerWeight: decimal('player_weight', { precision: 2 }),
  gameWon: boolean('game_won'),
});
